create table tb_account (id int8 generated by default as identity, balance float8, name varchar(255), primary key (id));
INSERT INTO tb_account (name, balance) VALUES ('Marcelo Bruno Henry', 45.89);
INSERT INTO tb_account (name, balance) VALUES ('Francisco Martin', 78.92);
INSERT INTO tb_account (name, balance) VALUES ('Daiane Cecília Teresinha', 568.98);
INSERT INTO tb_account (name, balance) VALUES ('Kauê Oliver Caldeira', 157.88);
INSERT INTO tb_account (name, balance) VALUES ('Raul Danilo Thomas', 12.87);

